on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
name: Fibonacci Actions Workflow
jobs:
  ci:
    runs-on: ubuntu-latest
    container: node:14.17.2

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint